spring.application.name=hospitalManagement

#DB configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update

#Every API endpoint must start with /api/v1
server.servlet.context-path=/api/v1


spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=false


#| Property                                            | Meaning                          | Why Needed                                  |
#| --------------------------------------------------- | -------------------------------- | ------------------------------------------- |
#| `spring.jpa.defer-datasource-initialization=true`   | Run SQL after JPA creates tables | Prevents "table not found" errors           |
#| `spring.sql.init.mode=always`                       | Always execute SQL init scripts  | Ensures SQL loads even with non-embedded DB |
#| `spring.sql.init.data-locations=classpath:timepass.sql` | Location of SQL file             | Spring knows where your inserts are         |


#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:timepass.sql

spring.jwt.token = BDXKJQWHLDASNCMNEBDKQEYTRI732649348UI3ODLKJQHDCANBCNVDHGFWT2I7RDHGHET736481YRKGDCMAHDFGEHJ

spring.security.oauth2.client.registration.google.client-id=asmcnhjda
spring.security.oauth2.client.registration.google.client-secret=12dedf

spring.security.oauth2.client.registration.github.client-id=Ov23liqJAKBJYlNAF8De
spring.security.oauth2.client.registration.github.client-secret=c5638bf1deae48ad7b53e48034fc1e3da036cdc8
